### ISSUE TITLE
500 Internal Server Error for GET /api/v1/users/profile

### ISSUE THREAD

**Issue by mickeymond** [DevLink-hub/DevLink-Backend#2]
@cameydanchi After signing up and logging in getting the User Profile throws the error below whether or not I pass in my Access Token.
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Error</title>
</head>

<body>
    <pre>Internal Server Error</pre>
</body>

</html>
```

**Comment by cameydanchi** [comment]
Mike fixed

**Comment by mickeymond** [comment]
@cameydanchi After looking at it again it returns the following
```
{
    "users": [
        {
            "firstName": "John",
            "lastName": "Smith",
            "email": "john.smith@example.com",
            "password": "$2b$12$4xL7g2r.BzLFyWG93sFda.bY.Jyf9ly.m2NsVLe0dFl6NDlw7840a",
            "userName": "johnsmith123",
            "createdAt": "2024-07-30T22:29:45.091Z",
            "updatedAt": "2024-07-30T22:29:45.091Z",
            "id": "66a969597586a66c5f40aca9"
        },
        {
            "firstName": "Michael",
            "lastName": "Hammond",
            "email": "mickeymond@yahoo.com",
            "password": "$2b$12$.LEDKxkaHatLysjuhKbUL.F/HbYtAZcq8yMxwy/DFm.fs6QiCOpZe",
            "userName": "mickeymond",
            "createdAt": "2024-08-02T12:15:44.390Z",
            "updatedAt": "2024-08-02T12:15:44.390Z",
            "id": "66accdf0e0c63845450ac90b"
        }
    ]
}
```
So is the goal for it to find the logged in user or all the users?

**Comment by mickeymond** [comment]
@cameydanchi It also now returns the password which is not acceptable.

**Comment by cameydanchi** [comment]
this is to find all users, but what should it be?

**Comment by mickeymond** [comment]
> this is to find all users, but what should it be?

@cameydanchi I am surprised that you are doing a find operation for getting a single user profile.
We need an operation like findById or findOne to have only 1 record.
Or is that not your intended goal?

**Comment by cameydanchi** [comment]
so mike should we find one by username or just find one... because of the route you gave was /profile

**Comment by cameydanchi** [comment]
if we are finding byId then the profile has to be /profile/:userId

**Comment by mickeymond** [comment]
> if we are finding byId then the profile has to be /profile/:userId

@cameydanchi If the user is logged in, can't we get their **id** from `req.session.user.id` OR `req.user.id`?

**Comment by cameydanchi** [comment]
We can , i did that and it returned one user for me and I changed it to getBYId .... I'll have to make a push for you to see my recent changes.

**Comment by cameydanchi** [comment]
i just did a pull please go through

**Comment by mickeymond** [comment]
@cameydanchi Are you sure you tested this code you added before deploying?

**Comment by cameydanchi** [comment]
yes

**Comment by cameydanchi** [comment]
the user/profile get the user who is currently logged in

**Comment by mickeymond** [comment]
@cameydanchi After our conversation, it means you should remove this endpoint to begin.
